default: &default
  adapter: postgresql
  database: bookstore_app_v2_database
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  database: bookstore_app_v2_database
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: bookstore_app_v2_database_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: bookstore_app_v2_database
  pool: 5
  timeout: 5000